server:
  port: 9227
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
spring:
  application:
    name: ics-park
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      maxFileSize: 5MB  #单位必须大写MB或不写(即为B)
      maxRequestSize: 10MB

